#!/usr/bin/env bash

read -p "start set up?(y/n)" confirmation

if [[ $confirmation == "y" ]]; then
    read -p "remove \"LICENSE\" and \"README.md\"?(y/n)" clean
    if [[ $clean == "y" ]]; then
        rm "LICENSE";
        rm "README.md";
    fi
    read -p "remove all git files?(y/n)" rmgit
    if [[ $rmgit == "y" ]]; then
        rm -rf ".git";
    fi
    read -p "add site directories?(y/n)"  dirsetup
    if [[ $dirsetup == "y" ]]; then
        while [[ $mkfolder != "stopdir" ]]; do
            read -p "enter the name of a directories until you are done, then type \"stopdir\"
\
" mkfolder
            mkdir $mkfolder;
        done
    fi

fi
